### ISSUE TITLE
How to make logging cooler

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#101]
- [x] Instead of `SmartDashboard.putNumber("arm setpoint pos", setpoint.position);` do `SmartDashboard.putNumber("arm/setpoint pos", setpoint.position);` and do this for every **value** for every **subsystem**. This will automatically group them in advantage scope and make it easier to find! 
  - [x] You can test advantage scope with the sim by changing roboRIO address in the advantage scope settings from `10.23.99.2` to `localhost`
![Screenshot from 2023-03-19 18-45-31](https://user-images.githubusercontent.com/19157596/226686921-d7c719e0-f358-4fc1-a134-926b9bbca97f.png)

- [x] Add PDP object (or rev equivalent?) to smartdashboard so all current values for all motors get logged
- [x] Add smartdashboard publishers for all motor setSpeeds maybe call them (motor percent output) so it doesn't get confused with a "velocity".
- [x] Look at herb's document to make sure all naming conventions are consistent
- [x] Should we: replace print commands with our own version that uses `DataLogManager.` so that prints go to the log file too?

Anything else?

**Comment by clocko3** [comment]
ok
