### ISSUE TITLE
Intaking until stall potential ideas

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#103]
Random thoughts/ideas/brainstorming:

1) Test the current version. Does it work? It should it looks pretty good! Get lots of data and graphs to see how intake velocity and current behave when intaking actual pieces.

2) Ask drive team about LEDs: turn green when piece and stay green? Turn green when piece but only for a second or two then go back to cone/cube color (*just* in case the mode accidentally gets toggled, so you can still see)? No turn green? BTW for the second one, you could make use of a `Timer` object in the LED subsystem to achieve the effect.

3) Because `intooked` is only set true after stall for 0.5 seconds, the button has to be held down for that time, which may be distracting / hard to do, and if the button is released early, `intooked` isn't set true and the piece will fall out :(. To address this *and* ensure the piece is all the way in before activating intooked, you can investigate using a `Timer` (a less hacky version of the `kFalling` debouncer idea) in the intake command so that after the button is let go it continues to intake for a period of time (maybe at a reduced speed), while still checking for stall and setting `intooked` to true if so.

**Comment by edf42001** [comment]
@clocko3 Is this issue resolved? :+1:

**Comment by clocko3** [comment]
yis
