### ISSUE TITLE
fix drive-only autons so they execute with no arm/elevator present

### ISSUE THREAD

**Issue by rebelreyek** [frc2399/2023-Season#129]
For our autonomous routines where we do not place any game pieces ([Engage](https://github.com/frc2399/2023-Season/blob/main/src/main/java/frc/robot/commands/auton/Engage.java#L25), and [Leave and Engage](https://github.com/frc2399/2023-Season/blob/main/src/main/java/frc/robot/commands/auton/LeaveEngage.java#L18)), the first command that we execute is zeroing the arm and lift on the robot. 

Although it is good practice to always zero these elements at the start of the match, there are very few (if any) strategic scenarios where we are not also placing a game piece unless our arm/elevator is broken. As a result, if we run our **Engage** or **Leave and Engage** autos without a funcitoning arm or elevator on the robot, the autonomous routine will never execute because it never gets past the initial zeroing command.

These commands _could_ be run in parallel (ie zeroing the arm while engaging) so that the zeroing command does not block other commands from executing. However, they are currently in a sequential command process (command 1 must complete before command 2 is started).

Alternatively, the command to zero the arm/lift could be removed entirely from these auton routines.

**Comment by ajagetia26** [comment]
Deleted both lines.
