### ISSUE TITLE
Simplify DriveTurnControls + ArcadeDrive

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#25]
Maise and Shrividya discovered the competition bot turned the wrong way (very odd, could be a couple of reasons). But this is a great time for the following: Currently to see what the heck the code is doing to the raw joystick values, one has to look in *three* locations:

https://github.com/frc2399/2023-Season/blob/c5ef3e86283721cd30023865d408d52b833e8beb/src/main/java/frc/robot/RobotContainer.java#L162-L164
https://github.com/frc2399/2023-Season/blob/c5ef3e86283721cd30023865d408d52b833e8beb/src/main/java/frc/robot/util/DriveTurnControls.java#L48
https://github.com/frc2399/2023-Season/blob/c5ef3e86283721cd30023865d408d52b833e8beb/src/main/java/frc/robot/commands/drivetrain/ArcadeDriveCmd.java#L38-L39

We can put everything in one file by:
* Moving the code inside of DriveTurnControls directly into arcade drive, and deleting DriveTurnControls
* passing the raw joystick getters into arcade drive command in robot container, no negative signs
* Replacing TURN/FORWARD_joystick invert constant with just the required -1 or +1. In this case the constants hide what the true value is, making it harder to see what's happening
* Could delete max_drive_speed constant while we're at it because that's just =1 as well right now

**Comment by Maheeshah07** [comment]
im mahee!!
