### ISSUE TITLE
updateForReal() should be removed from RealDrive and replaced with more appropriate method for IO

### ISSUE THREAD

**Issue by jeg100** [frc2399/2023-Season#26]
I forgot that we had added some code to get more current measurements in the same branch that we added the button-based auto commands on Sunday, which is now in the main branch. It was done not according to how I now understand the new IO file organization works. What needs to done is to rename the method in RealDrive from updateForReal to something like getMotorTemps, add an associated method to SimDrive, and remove the calls to updateForReal in DriveIO and DriveTrain.

**Comment by clocko3** [comment]
I made periodicUpdate() methods for all the IOs -- if there were any updateForXX I just moved it all into periodicUpdate()
