### ISSUE TITLE
Limit switch prevents elevator from going all the way to top

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#57]
The limit switch gets triggered so the motor stops outputting so the elevator falls down so the limit switch is no longer triggered so the elevator goes back up which triggers the limit switch etc.

One potential solution is to not use the sparkmax's built in limit switch cut off, turn that feature off for the top switch and do it ourselves:
```
  public void setSpeed(double speed) {
    if (topLimitSwitchPressed()) {
      speed = Math.min(speed, gravityCompensation);
    }

    elevatorIO.setSpeed(speed);
  }
```

something like this, `topLimitSwitchPressed` doesn't exist yet, and also watch out for line 77 (which should use setSpeed instead)

**Comment by clocko3** [comment]
ok smile
