### ISSUE TITLE
Cleanup EngageCmd

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#74]
Apparently, unlike most people who browse reddit when bored in class, I like to write detailed github issues to help parallelize our work.

To the team working on engage command, let's simplify.

`BEAM_BALANCED_GOAL_DEGREES` is just 0, so let's delete it and the error line and plug drivetrain.getGyroPitch directly into `drivePower = -Math.min(1/180. * error, 1)`
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L42

Our robot doesn't need this, so let's delete it (and the constant) and add it back later if we need to
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L45-L48

Not using these anymore:
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L64-L67
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L38-L39

There's duplicate code that limits the drive power, here and here:
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L43
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L50-L53

These could be simplified to
```java
drivePower = -1/180. * drivetrain.getGyroPitch();
drivePower = Math.max(Math.min(drivePower, 0.2), -0.2));
```

Remove the negative signs from `setMotors` ! Positive power should drive the robot forward. Instead, flip the sign of drivepower above somewhere. 
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L62

These don't really need to be global variables, and could be moved into the execute method. Though that's more of an opinion.
https://github.com/frc2399/2023-Season/blob/52e679fa1a7e12d2d38b341fcb98a01ca606fb60/src/main/java/frc/robot/commands/drivetrain/EngageCmd.java#L21-L23

Then make sure we didn't break anything.

**Comment by rblumin24** [comment]
Ethan needs to drink water!
