### ISSUE TITLE
An auto-reset arm encoder routine to make testing easier

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#77]
Here's my thought process:

1) `new InstantCommand(() -> a.disable())`: If you try to have the arm auto re calibrate when PID is running it will jitter weirdly.
2) `new RunCommand(() -> a.setSpeed(0.15)).withTimeout(0.2)`: What is this? Well, the command will end when the encoder velocity is 0, indicating the arm has hit the elevator. But the encoder velocity is also 0 in the millisecond the command starts, before the arm has started moving! So before moving onto the command in 3), let's wait a bit to let the arm start moving.
3) `new RunCommand(() -> a.setSpeed(0.15)).until(() -> Math.abs(a.getEncoderSpeed()) < 0.01)`: The main guy that does the work. Notice we're using setSpeed (not gravity compensation) because this assumes the encoder isn't calibrated properly. 
4) By adding a debouncer, we can make super duper sure the arm is firmly at the top of the elevator. If the arm gets stuck for a split second and the velocity returns 0, it would stop early (which would be bad)
```
Debouncer debouncer = new Debouncer(0.2);
new RunCommand(() -> a.setSpeed(0.15)).until(() -> debouncer.calculate(Math.abs(a.getEncoderSpeed()) < 0.01)),
```
5) ```new InstantCommand(() -> a.setPosition(Constants.ArmConstants.INITIAL_OFFSET))```: Do the reset
6) ```makeSetPositionCommand(arm, ArmConstants.INITIAL_OFFSET - 0.2)```: Once the encoder is calibrated, having the arm move to a arbitrary set position just to indicate the command is done could be helpful. 

Putting it all together,
```java
    private Command resetArmEncoderCommand(Arm a) {
        Debouncer debouncer = new Debouncer(0.2);
        return new SequentialCommandGroup(
            new PrintCommand("Resetting arm encoder"),
            new InstantCommand(() -> a.disable()),
            new RunCommand(() -> a.setSpeed(0.15)).withTimeout(0.2),
            new RunCommand(() -> a.setSpeed(0.15)).until(() -> debouncer.calculate(Math.abs(a.getEncoderSpeed()) < 0.01)),
            new InstantCommand(() -> a.setPosition(ArmConstants.INITIAL_OFFSET)),
            new PrintCommand("Arm encoder reset"),
            makeSetPositionCommand(arm, ArmConstants.INITIAL_OFFSET - 0.2)
        );
    }
```

You can actually test this in Sim first. Also I made up all these numbers. Finally, with the new intake you'll probably have to re-calibrate initial offset. Make sure this command is canceled when the button is released, (in case it gets stuck)

**Comment by clocko3** [comment]
doneeee
