### ISSUE TITLE
Some arm bugs (look carefully!)

### ISSUE THREAD

**Issue by edf42001** [frc2399/2023-Season#9]
The arm team might want to look carefully at `armPositionPublisher` and `armVelocityPublisher` in the `Arm` subsystem, and the `moveArm` command in `RobotContainer`. 

Also, consider replacing `DoublePublishers` with calls to `SmartDashboard.putNumber()` It worked for the path planning team!
https://github.com/frc2399/2023-Season/blob/9a59b7bde34fecfcd16b53145ada01ab9475d360/src/main/java/frc/robot/subsystems/DriveTrain.java#L155-L159

**Comment by rblumin24** [comment]
We got rid of the publishers and moved the SmartDashboard.putNumber calls into periodic. Yippee!! ᓚᘏᗢ ♪(´▽｀) ƪ(˘⌣˘)ʃ ✪ ω ✪(👉ﾟヮﾟ)👉👈(ﾟヮﾟ👈)ヾ(⌐■_■)ノ♪
