### ISSUE TITLE
Is there a bunch of positional error in our intake location?

### ISSUE THREAD

**Issue by wmarshall** [frc2399/2023-Season#94]
While journeying through our constants file as part of #92 and #93, I was surprised to see that our [ElevatorConstants.HEIGHT_TOLERANCE](https://github.com/frc2399/2023-Season/blob/main/src/main/java/frc/robot/Constants.java#L85) and [ArmConstants.AngleTolerance](https://github.com/frc2399/2023-Season/blob/main/src/main/java/frc/robot/Constants.java#L135) were both seeming so high. 

The lower bounds on these tolerances are our positional resolution for each subsystem, so I dug out some math:

1. With the elevator, we should have a positional resolution of [0.006"](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=157865990&range=F2)
2. With the arm, we should have a positional resolution of [0.114 degrees](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=721992374&range=E2)

Ultimately we're trying to control the location of the intake at the end of the arm in the middle of the elevator, so these tolerances compound and increase our potential total positional error.

To figure out how much our positional error might be, I did some more math. I found the distance from the arm axis to the farthest point on the intake in the CAD (27.019 inches) and did some calculations to figure out where that point would end up with:

1. [No Error](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=1131142677&range=A2)
2. [Max allowable elevator height, max allowable arm angle](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=1131142677&range=B2)
3. [Min allowed elevator height, min allowable arm angle](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=1131142677&range=C2)
4. [Max allowable elevator height, min allowable arm angle](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=1131142677&range=D2)
5. [Min allowed elevator height, max allowable arm angle](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=1131142677&range=E2)

The numbers vary as the arm sweeps through its rotation because displacements horizontally and vertically cancel out to various degrees, but things are pretty gnarly when the arm is horizontal (setpoint = 0 radians = 0 degrees). I got a max of [1.36 inches](https://docs.google.com/spreadsheets/d/1G4J8ZAfziwk9KAsrhscPvFny9eMHmLlBcsESP2hmzRQ/edit#gid=1131142677&range=L9) total positional displacement - so the tip of the intake could be anywhere in a 2.72 inch diameter circle around where it is supposed to be.

Is there some other mechanism we're using to reduce total positional error? Should we tighten our error tolerance closer to our theoretical minimums to reduce how much error we allow?

**Comment by edf42001** [comment]
Let's rename them to include the word "threshold" so it's more clear, update the comment and then this'll be good

**Comment by clocko3** [comment]
no smile no issue
